### ISSUE TITLE
Fili.firCoeffs is not a constructor

### ISSUE THREAD

**Issue by kevinmamaqi** [markert/fili.js#26]
Hi,

I just installed fili and followed the example with this code and I get the error message in the title:

```
//  Instance of a filter coefficient calculator
var firCalculator = new Fili.firCoeffs();


// calculate filter coefficients
var firFilterCoeffs = firCalculator.lowpass({
    order: 100, // filter order
    Fs: 1000, // sampling frequency
    Fc: 100
    // forbandpass and bandstop F1 and F2 must be provided instead of Fc
  });

// filter coefficients by Kaiser-Bessel window
var firFilterCoeffsK = firCalculator.kbFilter({
    order: 101, // filter order (must be odd)
    Fs: 1000, // sampling frequency
    Fa: 50, // rise, 0 for lowpass
    Fb: 100, // fall, Fs/2 for highpass
    Att: 100 // attenuation in dB
  });

// create a filter instance from the calculated coeffs
var firFilter = new Fili.FirFilter(filterCoeffs);
```

**Comment by markert** [comment]
Hi,

did you start with:

`var Fili = require('fili');`

**Comment by kevinmamaqi** [comment]
Yes I did. And all the files are in node_modules

Update with full code:

```
var Fili = require('fili');

//  Instance of a filter coefficient calculator
var firCalculator = new Fili.firCoeffs();

// calculate filter coefficients
var firFilterCoeffs = firCalculator.lowpass({
    order: 100, // filter order
    Fs: 1000, // sampling frequency
    Fc: 100 // cutoff frequency
    // forbandpass and bandstop F1 and F2 must be provided instead of Fc
  });

// filter coefficients by Kaiser-Bessel window
var firFilterCoeffsK = firCalculator.kbFilter({
    order: 101, // filter order (must be odd)
    Fs: 1000, // sampling frequency
    Fa: 50, // rise, 0 for lowpass
    Fb: 100, // fall, Fs/2 for highpass
    Att: 100 // attenuation in dB
  });

// create a filter instance from the calculated coeffs
var firFilter = new Fili.FirFilter(filterCoeffs);
```

NPM version: 6.9.0
Node version: 11.9.0


Full message in console:

/Users/kevinmamaqi/Desktop/lumc-ekg-app/new_app/ploty_try/index.js:5
var firCalculator = new Fili.firCoeffs();
                    ^

```
TypeError: Fili.firCoeffs is not a constructor
    at Object.<anonymous> (/myuser/fili_try/index.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

**Comment by kevinmamaqi** [comment]
Ok, found it. It should be Fili.FirCoeffs(); instead of Fili.firCoeffs();

**Comment by mmontag** [comment]
Noticed this too, I just submitted a PR to update the README.
